baseURL = 'http://wiki.openspartan.com/'
languageCode = 'en-us'
title = 'OpenSpartan Wiki'
theme = "docsy"
enableGitInfo = true

[outputs]
section = ["HTML", "RSS"]

contentDir = "content"

enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[params]
copyright = "Den Delimarsky"
privacy_policy = "https://policies.google.com/privacy"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/dend/openspartan-wiki"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/dend/openspartan-wiki"

github_branch= "main"

offlineSearch = true

prism_syntax_highlighting = false

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable = false
sidebar_cache_limit = 10
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

[params.ui.readingtime]
enable = false

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"] 

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"] 

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"] 
